tool
extends Node
# Appodeal Ad Networks for disable_network() method

const A4G: String = "a4g"
const ADCOLONY: String = "adcolony"
const ADMOB: String = "admob"
const ADMOB_MEDIATION: String = "admob_mediation"
const APPLOVIN: String = "applovin"
const BIDMACHINE: String = "bidmachine"
const BIDON: String = "bidon"
const BIGO_ADS: String = "bigo_ads"
const DT_EXCHANGE: String = "dt_exchange"
const GAM: String = "gam"
const META: String = "facebook"
const MINTEGRAL: String = "mintegral"
const MRAID: String = "mraid"
const MY_TARGET: String = "my_target"
const NOTSY: String = "notsy"
const INMOBI: String = "inmobi"
const IRONSOURCE: String = "ironsource"
const UNITY_ADS: String = "unity_ads"
const VAST: String = "vast"
const VUNGLE: String = "vungle"
const YANDEX: String = "yandex"
